name: Workflow - Merge Develop
on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
jobs:
  build_apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x gradlew
      - run: |
          KEYSTORE_P12_ASC_FILE="keystore.asc"
          echo "${{ secrets.KEYSTORE_P12}}">>"${KEYSTORE_P12_ASC_FILE}"
          ./shell/decrypt.sh "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_P12_ASC_FILE}"> "keystore.p12"
      - run: |
          KEYSTORE_PROPERTIES_ASC_FILE="keystore_properties.asc"
          echo "${{ secrets.KEYSTORE_PROPERTIES}}">>"${KEYSTORE_PROPERTIES_ASC_FILE}"
          ./shell/decrypt.sh "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${KEYSTORE_PROPERTIES_ASC_FILE}"> "keystore.properties"
      - run: |
          GOOGLE_SERVICES_ASC_FILE="google-services.asc"
          echo "${{ secrets.GOOGLE_SERVICES }}">>"${GOOGLE_SERVICES_ASC_FILE}"
          ./shell/decrypt.sh "$(echo "${{ secrets.PASSWORD }}" | base64 --decode)" \
            "${GOOGLE_SERVICES_ASC_FILE}"> "./app/google-services.json"
      - run: ./gradlew -Pversion.buildNumber="${GITHUB_RUN_NUMBER}" assembleDevelopmentRelease
      - uses: actions/upload-artifact@v3
        with:
          name: development-release-apk
          path: app/build/outputs/apk/development/release/app-development-release.apk